import { Ad } from "./types";

export const SAMPLE_CITIES = [
  { name: "Toutes les villes", count: 632 },
  { name: "Abidjan", count: 528 },
  { name: "Bouaké", count: 32 },
  { name: "Korhogo", count: 23 },
  { name: "Yamoussoukro", count: 18 },
  { name: "San-Pédro", count: 14 },
  { name: "Bingerville", count: 11 },
  { name: "Bassam", count: 6 },
];

export const INITIAL_ADS: Ad[] = [
  {
    id: "ad-1",
    user_id: "usr-1",
    user: {
      username: "Sexe_gamine",
      profile_photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
      gender: "Femme",
    },
    title: "Bingerville nouvelle fille jolie forme me déplace et reçois écrire...",
    description: "Disponible à Bingerville et alentours pour des moments agréables et discrets. Douce, propre, respectueuse et très attentionnée. Contactez-moi sur WhatsApp pour réserver votre moment.",
    city: "Bingerville",
    address: "Bingerville Carrefour CIAD",
    phone_number: "+2250708091011",
    contact_channels: "BOTH",
    accepted_clients: "HOMME",
    category: "escorte-girl",
    subcategories: ["Fellation", "Vaginal"],
    formula: "VIP",
    status: "ONLINE",
    is_boosted: false,
    photos: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 28 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: new Date(Date.now() + 28 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  {
    id: "ad-2",
    user_id: "usr-2",
    user: {
      username: "Caroline_Chic",
      profile_photo_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&auto=format&fit=crop&q=80",
      gender: "Femme",
    },
    title: "Nouvelle disponible ce soir à Cocody Angré 8e tranche",
    description: "Jeune dame très soignée, pulpeuse et sensuelle. Je reçois dans un cadre calme, climatisé et sécurisé. Hygiène irréprochable exigée des deux côtés.",
    city: "Abidjan",
    address: "Cocody Angré 8e Tranche",
    phone_number: "+2250504030201",
    contact_channels: "WHATSAPP",
    accepted_clients: "HOMME",
    category: "escorte-girl",
    subcategories: ["Fellation", "Vaginal", "Escorte événementielle"],
    formula: "VIP",
    status: "ONLINE",
    is_boosted: false,
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 25 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: new Date(Date.now() + 25 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "ad-3",
    user_id: "usr-3",
    user: {
      username: "Kingston_Spa",
      profile_photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
      gender: "Homme",
    },
    title: "Massage relaxant & bien-être Marcory Résidentiel à domicile ou hôtel",
    description: "Masseur professionnel certifié proposant massages thaïlandais, relaxants et californiens. Matériel de qualité et huiles essentielles bio. Déplacement possible sur tout Abidjan.",
    city: "Abidjan",
    address: "Marcory Résidentiel",
    phone_number: "+2250102030405",
    contact_channels: "CALL",
    accepted_clients: "TOUS",
    category: "massage",
    subcategories: ["Massage relaxant", "Massage à domicile", "Massage VIP"],
    formula: "PRO_PLUS",
    status: "ONLINE",
    is_boosted: true,
    boosted_at: new Date().toISOString(),
    photos: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 14 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: new Date(Date.now() + 14 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "ad-4",
    user_id: "usr-4",
    user: {
      username: "Yoyolaminette",
      profile_photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
      gender: "Femme",
    },
    title: "Nouvelle légère de Koumassi carrefour Ibo disponible en toute discrétion",
    description: "Belle jeune demoiselle accueillante et chaleureuse. Je vous reçois dans un cadre discret à Koumassi. Déplacement également possible.",
    city: "Abidjan",
    address: "Koumassi Carrefour Ibo",
    phone_number: "+2250777889900",
    contact_channels: "BOTH",
    accepted_clients: "HOMME",
    category: "escorte-girl",
    subcategories: ["Vaginal", "Fellation"],
    formula: "PRO",
    status: "ONLINE",
    is_boosted: false,
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 9 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: new Date(Date.now() + 6 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
  },
  {
    id: "ad-5",
    user_id: "usr-5",
    user: {
      username: "Vanessa_Trans",
      profile_photo_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&auto=format&fit=crop&q=80",
      gender: "Transgenre",
    },
    title: "Sublime femme transgenre raffinée pour moments coquins et inoubliables",
    description: "Élégante, féminine, très sociable et sans tabou. Reçoit dans un appartement cosy climatisé. Discrétion absolue garantie.",
    city: "Abidjan",
    address: "Plateau Dokui",
    phone_number: "+2250102039988",
    contact_channels: "WHATSAPP",
    accepted_clients: "HOMME",
    category: "transgenre",
    subcategories: ["Femme trans", "Escorte événementielle"],
    formula: "VIP",
    status: "ONLINE",
    is_boosted: false,
    photos: [
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 29 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: new Date(Date.now() + 29 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ad-6",
    user_id: "usr-6",
    user: {
      username: "Alex_Gentleman",
      profile_photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
      gender: "Homme",
    },
    title: "Escorte boy musclé et attentionné pour dames et couples respectueux",
    description: "Athlétique, galant, ouvert d'esprit et très soigné. Disponible pour dîners romantiques, soirées événementielles et rendez-vous privés.",
    city: "Abidjan",
    address: "Riviera Golf",
    phone_number: "+2250555667788",
    contact_channels: "BOTH",
    accepted_clients: "FEMME",
    category: "escorte-boy",
    subcategories: ["Actif", "Escorte événementielle"],
    formula: "STANDARD",
    status: "ONLINE",
    is_boosted: false,
    photos: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80",
    ],
    expires_at: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
    highlight_expires_at: null,
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
];
